In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt



ModuleNotFoundError: No module named 'pandas'

In [ ]:
df = pd.read_csv("/content/datasetagri(updated3) (1).csv")

In [ ]:
df.head(5)

pH (1:2.5) EC dS/m (1:2.5)   OC% P2O5 (kg/ha) K2O (kg/ha) S (ppm) B (ppm)  \
0        NaN             NaN   NaN          NaN         NaN     NaN     NaN   
1       6.16            0.14  1.68        29.59      536.25   6.550   0.113   
2       7.28            0.07  0.83        55.31      156.80   5.147      ND   
3       6.20            1.13  0.55        36.74      100.28   9.357      ND   
4       6.85            0.15  1.01        85.34      332.43   5.147      ND   

  Fe (ppm) Mn (ppm) Zn (ppm) Cu (ppm) Unnamed: 11  
0      NaN      NaN      NaN      NaN      rating  
1    18.77    61.70     2.33     6.46   Very High  
2    13.49    21.60     1.15     3.14      Medium  
3    15.28    38.06     0.99     5.82         Low  
4    19.25    43.78     1.43     4.16   Very High

In [ ]:
df = df.iloc[1:,:]

In [ ]:
df.head(5)

pH (1:2.5) EC dS/m (1:2.5)   OC% P2O5 (kg/ha) K2O (kg/ha) S (ppm) B (ppm)  \
1       6.16            0.14  1.68        29.59      536.25   6.550   0.113   
2       7.28            0.07  0.83        55.31      156.80   5.147      ND   
3       6.20            1.13  0.55        36.74      100.28   9.357      ND   
4       6.85            0.15  1.01        85.34      332.43   5.147      ND   
5       6.26            0.27  1.36         4.71      151.24   7.486      ND   

  Fe (ppm) Mn (ppm) Zn (ppm) Cu (ppm) Unnamed: 11  
1    18.77    61.70     2.33     6.46   Very High  
2    13.49    21.60     1.15     3.14      Medium  
3    15.28    38.06     0.99     5.82         Low  
4    19.25    43.78     1.43     4.16   Very High  
5    22.27    70.48     1.27     8.17      Medium

In [ ]:
df.columns

Index(['pH (1:2.5)', 'EC dS/m (1:2.5)', 'OC%', 'P2O5 (kg/ha)', 'K2O (kg/ha)',
       'S (ppm)', 'B (ppm)', 'Fe (ppm)', 'Mn (ppm)', 'Zn (ppm)', 'Cu (ppm)',
       'Unnamed: 11'],
      dtype='object')

In [ ]:
df = df.rename(columns={'Unnamed: 11':'rating'})

In [ ]:
df.columns

Index(['pH (1:2.5)', 'EC dS/m (1:2.5)', 'OC%', 'P2O5 (kg/ha)', 'K2O (kg/ha)',
       'S (ppm)', 'B (ppm)', 'Fe (ppm)', 'Mn (ppm)', 'Zn (ppm)', 'Cu (ppm)',
       'rating'],
      dtype='object')

In [ ]:
df.head(5)

pH (1:2.5) EC dS/m (1:2.5)   OC% P2O5 (kg/ha) K2O (kg/ha) S (ppm) B (ppm)  \
1       6.16            0.14  1.68        29.59      536.25   6.550   0.113   
2       7.28            0.07  0.83        55.31      156.80   5.147      ND   
3       6.20            1.13  0.55        36.74      100.28   9.357      ND   
4       6.85            0.15  1.01        85.34      332.43   5.147      ND   
5       6.26            0.27  1.36         4.71      151.24   7.486      ND   

  Fe (ppm) Mn (ppm) Zn (ppm) Cu (ppm)     rating  
1    18.77    61.70     2.33     6.46  Very High  
2    13.49    21.60     1.15     3.14     Medium  
3    15.28    38.06     0.99     5.82        Low  
4    19.25    43.78     1.43     4.16  Very High  
5    22.27    70.48     1.27     8.17     Medium

In [ ]:
df.isnull().sum()

pH (1:2.5)           2
EC dS/m (1:2.5)      2
OC%                  2
P2O5 (kg/ha)         2
K2O (kg/ha)          2
S (ppm)              2
B (ppm)              2
Fe (ppm)           123
Mn (ppm)           123
Zn (ppm)           123
Cu (ppm)           123
rating               0
dtype: int64

In [ ]:
df['pH (1:2.5)'].mode()

0    6.60
1    7.10
2     7.2
3    7.25
dtype: object

In [ ]:
df['pH (1:2.5)'].fillna(7.10,inplace = True)

In [ ]:
df['EC dS/m (1:2.5)'].mode()

0    0.08
1    0.10
dtype: object

In [ ]:
df['EC dS/m (1:2.5)'].fillna(0.10,inplace = True) 


In [ ]:
df['OC%'].mode()

0    0.80
dtype: object

In [ ]:
df['OC%'].fillna(0.80,inplace = True) 


In [ ]:
df['P2O5 (kg/ha)'].mode()

0    15.68
dtype: object

In [ ]:
df['P2O5 (kg/ha)'].fillna(15.68,inplace = True) 


In [ ]:
df['K2O (kg/ha)'].mode()

0         -
1    125.76
2    165.33
3    175.50
4    177.67
5    202.74
6    359.26
7    457.92
dtype: object

In [ ]:
df['K2O (kg/ha)'].fillna(177.67,inplace = True)

In [ ]:
df['Mn (ppm)'].mode()

0    11.15
1    16.23
2     5.04
3    65.86
dtype: object

In [ ]:
df['Mn (ppm)'].fillna(5.04,inplace = True)

In [ ]:
df['S (ppm)'].mode()

0    1.871
dtype: object

In [ ]:
df['S (ppm)'].fillna(1.871,inplace = True)

In [ ]:
df['Zn (ppm)'].mode()

0    0.26
dtype: object

In [ ]:
df['Zn (ppm)'].fillna(0.26,inplace = True)

In [ ]:
df['Cu (ppm)'].mode()

0    1.65
1    2.29
2    4.48
dtype: object

In [ ]:
df['Cu (ppm)'].fillna(2.29,inplace = True)

In [ ]:
df['B (ppm)'].replace(to_replace="ND",
           value="0")

1      0.113
2          0
3          0
4          0
5          0
       ...  
251    1.021
252    0.908
253    0.681
254      NaN
255      NaN
Name: B (ppm), Length: 255, dtype: object

In [ ]:
df['B (ppm)'] = df['B (ppm)'].fillna(0,inplace = True)

In [ ]:
df['Fe (ppm)'].mode()

0    22.27
dtype: object

In [ ]:
df['Fe (ppm)'].fillna(22.27,inplace = True)

In [ ]:
df.isnull().sum()

pH (1:2.5)           0
EC dS/m (1:2.5)      0
OC%                  0
P2O5 (kg/ha)         0
K2O (kg/ha)          0
S (ppm)              0
B (ppm)            255
Fe (ppm)             0
Mn (ppm)             0
Zn (ppm)             0
Cu (ppm)             0
rating               0
dtype: int64

In [ ]:
df.head(15)

pH (1:2.5) EC dS/m (1:2.5)   OC% P2O5 (kg/ha) K2O (kg/ha) S (ppm) B (ppm)  \
1        6.16            0.14  1.68        29.59      536.25   6.550    None   
2        7.28            0.07  0.83        55.31      156.80   5.147    None   
3        6.20            1.13  0.55        36.74      100.28   9.357    None   
4        6.85            0.15  1.01        85.34      332.43   5.147    None   
5        6.26            0.27  1.36         4.71      151.24   7.486    None   
6        7.00            0.17  0.61        61.06      449.38   5.147    None   
7        6.30            0.08  0.92        17.05      208.43   2.807    None   
8        7.35            0.11  0.66        20.94      402.36   3.275    None   
9        6.60            0.59  0.83        10.85      177.40  24.797    None   
10       6.65            0.11  1.16        33.55      123.87   4.211    None   
11       7.10            0.06  0.41        13.17      146.63   4.679    None   
12       7.15            0.24  2.97        88.75      311.02   7.954    None   
13       8.10            0.10  0.84        26.43      529.07   1.404    None   
14       7.45            0.10  0.46       416.26      188.10  10.293    None   
15       7.25            0.08  1.03        12.40      236.48   5.147    None   

   Fe (ppm) Mn (ppm) Zn (ppm) Cu (ppm)     rating  
1     18.77    61.70     2.33     6.46  Very High  
2     13.49    21.60     1.15     3.14     Medium  
3     15.28    38.06     0.99     5.82        Low  
4     19.25    43.78     1.43     4.16  Very High  
5     22.27    70.48     1.27     8.17     Medium  
6     15.66    19.62     1.39     4.21  Very High  
7     22.55   110.42     1.57     7.48       High  
8     13.87    74.64     1.90     7.00  Very High  
9     10.47     9.58     1.39     2.45     Medium  
10    11.32    22.32     1.46     2.13        Low  
11    15.38    22.46     1.13     4.27        Low  
12    32.45    11.15     6.09     3.14  Very High  
13     3.77     5.04     0.89     0.52  Very High  
14    16.42    14.87     2.21     4.21     Medium  
15    12.83    63.76     6.63     3.87       High

In [ ]:
df['B (ppm)'].dtype

dtype('O')

In [ ]:
df = df.drop('B (ppm)',axis = 1)

In [ ]:
df.shape

(255, 11)

In [ ]:
df.head(15)

pH (1:2.5) EC dS/m (1:2.5)   OC% P2O5 (kg/ha) K2O (kg/ha) S (ppm) Fe (ppm)  \
1        6.16            0.14  1.68        29.59      536.25   6.550    18.77   
2        7.28            0.07  0.83        55.31      156.80   5.147    13.49   
3        6.20            1.13  0.55        36.74      100.28   9.357    15.28   
4        6.85            0.15  1.01        85.34      332.43   5.147    19.25   
5        6.26            0.27  1.36         4.71      151.24   7.486    22.27   
6        7.00            0.17  0.61        61.06      449.38   5.147    15.66   
7        6.30            0.08  0.92        17.05      208.43   2.807    22.55   
8        7.35            0.11  0.66        20.94      402.36   3.275    13.87   
9        6.60            0.59  0.83        10.85      177.40  24.797    10.47   
10       6.65            0.11  1.16        33.55      123.87   4.211    11.32   
11       7.10            0.06  0.41        13.17      146.63   4.679    15.38   
12       7.15            0.24  2.97        88.75      311.02   7.954    32.45   
13       8.10            0.10  0.84        26.43      529.07   1.404     3.77   
14       7.45            0.10  0.46       416.26      188.10  10.293    16.42   
15       7.25            0.08  1.03        12.40      236.48   5.147    12.83   

   Mn (ppm) Zn (ppm) Cu (ppm)     rating  
1     61.70     2.33     6.46  Very High  
2     21.60     1.15     3.14     Medium  
3     38.06     0.99     5.82        Low  
4     43.78     1.43     4.16  Very High  
5     70.48     1.27     8.17     Medium  
6     19.62     1.39     4.21  Very High  
7    110.42     1.57     7.48       High  
8     74.64     1.90     7.00  Very High  
9      9.58     1.39     2.45     Medium  
10    22.32     1.46     2.13        Low  
11    22.46     1.13     4.27        Low  
12    11.15     6.09     3.14  Very High  
13     5.04     0.89     0.52  Very High  
14    14.87     2.21     4.21     Medium  
15    63.76     6.63     3.87       High

In [ ]:
df['rating'].unique()

array(['Very High', 'Medium', 'Low', 'High', 'Very Low'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
la = LabelEncoder()

In [ ]:
df['rating'] = la.fit_transform(df.rating)

In [ ]:
df.head(15)

pH (1:2.5) EC dS/m (1:2.5)   OC% P2O5 (kg/ha) K2O (kg/ha) S (ppm) Fe (ppm)  \
1        6.16            0.14  1.68        29.59      536.25   6.550    18.77   
2        7.28            0.07  0.83        55.31      156.80   5.147    13.49   
3        6.20            1.13  0.55        36.74      100.28   9.357    15.28   
4        6.85            0.15  1.01        85.34      332.43   5.147    19.25   
5        6.26            0.27  1.36         4.71      151.24   7.486    22.27   
6        7.00            0.17  0.61        61.06      449.38   5.147    15.66   
7        6.30            0.08  0.92        17.05      208.43   2.807    22.55   
8        7.35            0.11  0.66        20.94      402.36   3.275    13.87   
9        6.60            0.59  0.83        10.85      177.40  24.797    10.47   
10       6.65            0.11  1.16        33.55      123.87   4.211    11.32   
11       7.10            0.06  0.41        13.17      146.63   4.679    15.38   
12       7.15            0.24  2.97        88.75      311.02   7.954    32.45   
13       8.10            0.10  0.84        26.43      529.07   1.404     3.77   
14       7.45            0.10  0.46       416.26      188.10  10.293    16.42   
15       7.25            0.08  1.03        12.40      236.48   5.147    12.83   

   Mn (ppm) Zn (ppm) Cu (ppm)  rating  
1     61.70     2.33     6.46       3  
2     21.60     1.15     3.14       2  
3     38.06     0.99     5.82       1  
4     43.78     1.43     4.16       3  
5     70.48     1.27     8.17       2  
6     19.62     1.39     4.21       3  
7    110.42     1.57     7.48       0  
8     74.64     1.90     7.00       3  
9      9.58     1.39     2.45       2  
10    22.32     1.46     2.13       1  
11    22.46     1.13     4.27       1  
12    11.15     6.09     3.14       3  
13     5.04     0.89     0.52       3  
14    14.87     2.21     4.21       2  
15    63.76     6.63     3.87       0

In [ ]:
df.shape

(255, 11)

In [ ]:
df['rating'].unique()

array([3, 2, 1, 0, 4])

In [ ]:
# df["Cu (ppm)"] = df["Cu (ppm)"].astype(float)

In [ ]:
for i in df.columns:
    cnt=0
    # print(i)
    for j in df[i]:
        # print(j)
        if j == 'ND' or j =='-':
            df.drop(df.index[cnt],inplace=True)
            cnt-=1
            # break
        cnt+=1

In [ ]:
x = df.iloc[:,:-1]
x

pH (1:2.5) EC dS/m (1:2.5)   OC% P2O5 (kg/ha) K2O (kg/ha) S (ppm)  \
1         6.16            0.14  1.68        29.59      536.25   6.550   
2         7.28            0.07  0.83        55.31      156.80   5.147   
3         6.20            1.13  0.55        36.74      100.28   9.357   
4         6.85            0.15  1.01        85.34      332.43   5.147   
5         6.26            0.27  1.36         4.71      151.24   7.486   
..         ...             ...   ...          ...         ...     ...   
251        7.3           0.127  0.69        76.64      199.49   1.871   
252       6.75           0.068  0.50        45.29      165.33   5.147   
253        7.4           0.348  1.39       714.12     1017.89   6.082   
254        7.1             0.1   0.8        15.68      177.67   1.871   
255        7.1             0.1   0.8        15.68      177.67   1.871   

    Fe (ppm) Mn (ppm) Zn (ppm) Cu (ppm)  
1      18.77    61.70     2.33     6.46  
2      13.49    21.60     1.15     3.14  
3      15.28    38.06     0.99     5.82  
4      19.25    43.78     1.43     4.16  
5      22.27    70.48     1.27     8.17  
..       ...      ...      ...      ...  
251    22.27     5.04     0.26     2.29  
252    22.27     5.04     0.26     2.29  
253    22.27     5.04     0.26     2.29  
254    22.27     5.04     0.26     2.29  
255    22.27     5.04     0.26     2.29  

[242 rows x 10 columns]

In [ ]:
y = df.iloc[:,-1]
y

1      3
2      2
3      1
4      3
5      2
      ..
251    2
252    2
253    3
254    4
255    4
Name: rating, Length: 242, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
scaled_Xtrain = sc.fit_transform(X_train)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
n_estimators=[64,100,128,200]
max_features= [2,3,4]
bootstrap = [True,False]
oob_score = [True,False]

In [ ]:
param_grid = {'n_estimators':n_estimators,
             'max_features':max_features,
             'bootstrap':bootstrap,
             'oob_score':oob_score} 

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier()
grid = GridSearchCV(rfc,param_grid)

In [ ]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
60 fits failed out of a total of 240.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py", line 434, in fit
    raise ValueError("Out of bag estimation only available if bootstrap=True")
ValueError: Out of bag estimation only available if bootstrap=True

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/p

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'bootstrap': [True, False], 'max_features': [2, 3, 4],
                         'n_estimators': [64, 100, 128, 200],
                         'oob_score': [True, False]})

In [ ]:
grid.best_params_

{'bootstrap': True, 'max_features': 4, 'n_estimators': 200, 'oob_score': True}

In [ ]:
predictions = grid.predict(X_test)

In [ ]:
predictions

array([3, 0, 3, 3, 0, 1, 3, 1, 2, 2, 3, 0, 0, 0, 4, 3, 3, 0, 0, 1, 1, 1,
       3, 3, 0, 0, 2, 2, 3, 1, 1, 3, 0, 2, 0, 3, 3, 3, 3, 3, 2, 0, 2, 3,
       3, 3, 0, 3, 4, 3, 3, 3, 3, 2, 0, 4, 3, 3, 3, 4, 0, 1, 3, 0, 2, 3,
       2, 3, 3, 3, 0, 3, 0, 1, 3, 0, 0, 3, 3, 3])

In [ ]:
grid.predict([[6.16,0.14	,1.68	,29.59	,536.25	,6.550,	18.77	,61.70	,2.33	,6.46]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([3])

In [ ]:
grid.predict([[6.20	,1.13	,0.55	,36.74	,100.28	,9.357,	15.28,	38.06	,0.99	,5.82	]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

In [ ]:
import pickle as pkl

In [ ]:
with open('ALGO.pickle','wb') as f:
  pkl.dump(grid,f)

In [ ]:
with open('ALGO.pickle','rb') as f:
  model = pkl.load(f)

In [ ]:
model.predict([[6.20	,1.13	,0.55	,36.74	,100.28	,9.357,	15.28,	38.06	,0.99	,5.82	]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])